[build]
  command = "npm run build"
  publish = "build"
  base = "/"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "build"
  framework = "#custom"
